# Generated by Django 3.2.9 on 2021-11-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Todo',
        ),
    ]
